// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cyCudm5FpG5eYjn85tGpB904NBhuTZ8',
    appId: '1:968505550588:web:0eac44163a81e176791979',
    messagingSenderId: '968505550588',
    projectId: 'flutter-auth-system-1',
    authDomain: 'flutter-auth-system-1.firebaseapp.com',
    storageBucket: 'flutter-auth-system-1.firebasestorage.app',
    measurementId: 'G-4PQQJNDG7H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCECTxRAADyoUsbCj_4Pcfia-gGrslrVe4',
    appId: '1:968505550588:ios:032ac2ec9ab872f4791979',
    messagingSenderId: '968505550588',
    projectId: 'flutter-auth-system-1',
    storageBucket: 'flutter-auth-system-1.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_cyCudm5FpG5eYjn85tGpB904NBhuTZ8',
    appId: '1:968505550588:web:ed01a216ef5b35d4791979',
    messagingSenderId: '968505550588',
    projectId: 'flutter-auth-system-1',
    authDomain: 'flutter-auth-system-1.firebaseapp.com',
    storageBucket: 'flutter-auth-system-1.firebasestorage.app',
    measurementId: 'G-WNZG5265CY',
  );
}
