// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdnnrj6-G9BGoPHOKLAtNs1pWLcGj6DL8',
    appId: '1:162217174147:android:0ac29f4828c9a141c127b6',
    messagingSenderId: '162217174147',
    projectId: 'fir-auth-system-c3176',
    storageBucket: 'fir-auth-system-c3176.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLPPND2_K2cCJvIff3U5uvEQuXkkAFF4',
    appId: '1:162217174147:ios:6d5d483a4f6b48efc127b6',
    messagingSenderId: '162217174147',
    projectId: 'fir-auth-system-c3176',
    storageBucket: 'fir-auth-system-c3176.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterJourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6c1JyJWh9vvpNqUcqXCrpKZ2228_pRJc',
    appId: '1:162217174147:web:8c54901dcf008d15c127b6',
    messagingSenderId: '162217174147',
    projectId: 'fir-auth-system-c3176',
    authDomain: 'fir-auth-system-c3176.firebaseapp.com',
    storageBucket: 'fir-auth-system-c3176.firebasestorage.app',
    measurementId: 'G-7NJ7LXQD56',
  );
}
